trigger:
- main

pool:
  name: cicd pool

variables:
  RESOURCE_GROUP: cd-aks-rg
  LOCATION: eastus
  ACR_NAME: kuladeepacr12345
  AKS_NAME: cdakscluster

steps:

- task: AzureCLI@2
  displayName: Deploy AKS + Prometheus
  inputs:
    azureSubscription: azure-conn
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |

      echo "Creating Resource Group"
      az group create \
        --name $RESOURCE_GROUP \
        --location $LOCATION

      echo "Creating ACR"
      az acr create \
        --resource-group $RESOURCE_GROUP \
        --name $ACR_NAME \
        --sku Basic

      echo "Creating AKS"
      az aks create \
        --resource-group $RESOURCE_GROUP \
        --name $AKS_NAME \
        --node-count 1 \
        --generate-ssh-keys

      echo "Getting AKS credentials"
      az aks get-credentials \
        --resource-group $RESOURCE_GROUP \
        --name $AKS_NAME \
        --overwrite-existing

      echo "Checking cluster connection"
      kubectl get nodes

      echo "Create monitoring namespace"
      kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -

      echo "Deploy Prometheus"
      helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      helm repo update

      helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
        --namespace monitoring